language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4.1

# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python multi_sessions/tests.py