language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=1.9.1
  - DJANGO_VERSION=1.7.1

# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q django-redis-sessions>=0.3.1

# command to run tests
script: python multi_sessions/tests.py
