language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5

# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q django-redis-sessions>=0.3.1

# command to run tests
script: python multi_sessions/tests.py